version: '3'

services:

  influxdb:
    build: ./docker/influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./docker/influxdb/volume:/var/lib/influxdb2

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hW~7;?I/Bukc3GA
      - MYSQL_DATABASE=eight_sleep

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  php:
    build: ./docker/php
    restart: unless-stopped
    volumes:
      - .:/var/www/html              # must match vhost's DocumentRoot
    working_dir: /var/www/html       # commands run from this path
    depends_on: [influxdb, mysql]
